/* Panel privado: sólo funciona para perfiles con role = admin en Supabase. */
(function () {
  const state = { tab: 'dashboard', clubs: [], events: [], photos: [], orders: [] };
  const content = () => document.querySelector('#admin-content');
  const money = (v) => Shop.money(v);
  const fmtDate = (d) => d ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium' }).format(new Date(`${d}T12:00:00`)) : 'Sin fecha';
  const dateValue = (v) => v ? String(v).slice(0, 10) : '';
  const esc = (value = '') => String(value).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[c]));
  const selected = (a, b) => a === b ? 'selected' : '';
  const checked = (x) => x ? 'checked' : '';
  const setTab = (tab) => { state.tab = tab; document.querySelectorAll('[data-tab]').forEach(b => b.classList.toggle('active', b.dataset.tab === tab)); render(); };
  const head = (title, text, action = '') => `<div class="admin-page-head"><div><h1>${title}</h1><p>${text}</p></div>${action}</div>`;

  async function refreshCore() { [state.clubs, state.events] = await Promise.all([AppData.clubs({ published: false }), AppData.events({ published: false })]); }
  async function refreshPhotos() { state.photos = await AppData.adminPhotos(); }
  async function refreshOrders() { state.orders = await AppData.orders(); }
  async function render() {
    try {
      if (state.tab === 'dashboard') await dashboard();
      if (state.tab === 'clubs') await clubsPage();
      if (state.tab === 'events') await eventsPage();
      if (state.tab === 'upload') await uploadPage();
      if (state.tab === 'photos') await photosPage();
      if (state.tab === 'orders') await ordersPage();
    } catch (error) { console.error(error); content().innerHTML = `${head('No pudimos cargar esta sección', 'Revisá la conexión y las políticas de Supabase.')}<div class="admin-card">${esc(error.message || 'Error inesperado')}</div>`; }
  }
  async function dashboard() {
    await Promise.all([refreshCore(), refreshPhotos(), refreshOrders()]);
    content().innerHTML = `${head('Resumen', 'Una vista rápida de tu plataforma.')}<div class="stat-grid"><article class="stat-card"><span>Clubes</span><b>${state.clubs.length}</b></article><article class="stat-card"><span>Eventos</span><b>${state.events.length}</b></article><article class="stat-card"><span>Fotografías</span><b>${state.photos.length}</b></article><article class="stat-card"><span>Pedidos</span><b>${state.orders.length}</b></article></div><div class="admin-card" style="margin-top:22px"><h2>Próximo paso</h2><p class="admin-note">Para publicar una nueva cobertura: creá el club si hace falta, registrá el evento y después ingresá a “Subir fotos”. Las previsualizaciones se crean con la marca de agua configurada, mientras los originales quedan en el bucket privado.</p><button class="button button-primary" data-go-upload>Subir fotografías</button></div>`;
    content().querySelector('[data-go-upload]').onclick = () => setTab('upload');
  }
  function clubForm(club = {}) { return `<form id="club-form"><input type="hidden" name="id" value="${club.id || ''}"><div class="admin-form-grid"><label>Nombre<input name="name" required value="${esc(club.name)}" placeholder="Ej. Club Atlético... "></label><label>Nombre corto<input name="short_name" required maxlength="30" value="${esc(club.short_name)}" placeholder="Ej. C. Atlético"></label><label class="full">Descripción<textarea name="description" rows="3" placeholder="Texto breve para visitantes">${esc(club.description)}</textarea></label><label>Logo (archivo opcional)<input class="file-input" name="logo" type="file" accept="image/*"></label><label>Portada (archivo opcional)<input class="file-input" name="cover" type="file" accept="image/*"></label><label class="check-label full"><input name="published" type="checkbox" ${checked(club.published ?? true)}> Mostrar este club públicamente</label></div><button class="button button-primary" type="submit">${club.id ? 'Guardar cambios' : 'Crear club'}</button>${club.id ? ' <button class="text-button" type="button" data-reset-club>Cancelar edición</button>' : ''}</form>`; }
  async function clubsPage(edit) {
    await refreshCore(); const current = edit || {};
    content().innerHTML = `${head('Clubes', 'Creá y administrá los equipos que verán los visitantes.')}<div class="admin-grid"><aside class="admin-card"><h2>${current.id ? 'Editar club' : 'Nuevo club'}</h2>${clubForm(current)}</aside><section class="admin-card"><h2>Clubes existentes (${state.clubs.length})</h2><div class="admin-list">${state.clubs.length ? state.clubs.map(c => `<article class="admin-list-row">${UI.image(c.cover_path || c.logo_path, c.name)}<div><h3>${esc(c.name)}</h3><p>${c.events?.[0]?.count || 0} eventos · ${c.published ? 'PUBLICADO' : 'OCULTO'}</p></div><div class="row-actions"><button class="small-button" data-club-edit="${c.id}">Editar</button><button class="small-button" data-club-toggle="${c.id}">${c.published ? 'Ocultar' : 'Publicar'}</button><button class="small-button danger" data-club-delete="${c.id}">Eliminar</button></div></article>`).join('') : '<p class="admin-empty">Todavía no creaste clubes.</p>'}</div></section></div>`;
    bindClubPage();
  }
  async function uploadCover(file, folder, id) { if (!file?.size) return null; if (file.size > 12 * 1024 * 1024) throw new Error('La imagen de portada no puede superar los 12 MB.'); const path = `${folder}/${id}-${crypto.randomUUID()}-${AppData.safeName(file.name)}`; await AppData.upload('previews', path, file); return path; }
  function bindClubPage() {
    content().querySelector('#club-form').addEventListener('submit', async (e) => {
      e.preventDefault(); const form = e.currentTarget; if (!form.reportValidity()) return; const button = form.querySelector('[type=submit]'); const fd = new FormData(form); const id = fd.get('id'); const values = { name: fd.get('name').trim(), short_name: fd.get('short_name').trim(), description: fd.get('description').trim() || null, published: fd.has('published') };
      UI.setLoading(button, true);
      try { const club = id ? await AppData.updateClub(id, values) : await AppData.createClub(values); const logo = await uploadCover(fd.get('logo'), 'club-logos', club.id); const cover = await uploadCover(fd.get('cover'), 'club-covers', club.id); if (logo || cover) await AppData.updateClub(club.id, { ...(logo ? { logo_path: logo } : {}), ...(cover ? { cover_path: cover } : {}) }); UI.toast('Club guardado.', 'success'); clubsPage(); }
      catch (error) { UI.toast(error.message || 'No pudimos guardar el club.'); console.error(error); } finally { UI.setLoading(button, false); }
    });
    content().addEventListener('click', async (e) => {
      if (e.target.matches('[data-reset-club]')) return clubsPage(); const id = e.target.dataset.clubEdit || e.target.dataset.clubToggle || e.target.dataset.clubDelete; if (!id) return; const club = state.clubs.find(c => c.id === id);
      try { if (e.target.dataset.clubEdit) clubsPage(club); if (e.target.dataset.clubToggle) { await AppData.updateClub(id, { published: !club.published }); UI.toast('Estado actualizado.', 'success'); clubsPage(); } if (e.target.dataset.clubDelete && confirm(`¿Eliminar “${club.name}”? También se eliminarán sus eventos y fotos. Esta acción no se puede deshacer.`)) { await AppData.deleteClub(id); UI.toast('Club eliminado.', 'success'); clubsPage(); } } catch (error) { UI.toast(error.message || 'No se pudo completar la acción.'); }
    });
  }
  function eventForm(event = {}) { const options = state.clubs.map(c => `<option value="${c.id}" ${selected(c.id, event.club_id)}> ${esc(c.name)}</option>`).join(''); return `<form id="event-form"><input type="hidden" name="id" value="${event.id || ''}"><div class="admin-form-grid"><label>Club<select name="club_id" required><option value="">Seleccionar club</option>${options}</select></label><label>Rival<input name="opponent" value="${esc(event.opponent)}" placeholder="Ej. Deportivo Norte"></label><label class="full">Nombre del evento<input name="name" required value="${esc(event.name)}" placeholder="Ej. Primera División - Fecha 4"></label><label>Fecha<input name="event_date" required type="date" value="${dateValue(event.event_date)}"></label><label>Hora<input name="event_time" type="time" value="${event.event_time ? String(event.event_time).slice(0,5) : ''}"></label><label>Estadio / lugar<input name="venue" value="${esc(event.venue)}" placeholder="Ej. Estadio Municipal"></label><label>Precio inicial por foto (ARS)<input name="default_price_ars" required type="number" min="0" step="1" value="${event.default_price_ars ?? PRECIOS.FOTO_INDIVIDUAL}"></label><label class="full">Descripción<textarea name="description" rows="3">${esc(event.description)}</textarea></label><label class="full">Portada del evento (archivo opcional)<input class="file-input" name="cover" type="file" accept="image/*"></label><label class="check-label"><input name="published" type="checkbox" ${checked(event.published ?? true)}> Publicado</label><label class="check-label"><input name="featured" type="checkbox" ${checked(event.featured)}> Destacar en inicio</label></div><button class="button button-primary" type="submit">${event.id ? 'Guardar cambios' : 'Crear evento'}</button>${event.id ? ' <button class="text-button" data-reset-event type="button">Cancelar edición</button>' : ''}</form>`; }
  async function eventsPage(edit) {
    await refreshCore(); content().innerHTML = `${head('Eventos', 'Cada evento contiene su propia galería y precio inicial.')}<div class="admin-grid"><aside class="admin-card"><h2>${edit?.id ? 'Editar evento' : 'Nuevo evento'}</h2>${state.clubs.length ? eventForm(edit) : '<p class="admin-empty">Primero creá al menos un club.</p>'}</aside><section class="admin-card"><h2>Eventos existentes (${state.events.length})</h2><div class="admin-list">${state.events.length ? state.events.map(e => `<article class="admin-list-row">${UI.image(e.cover_path, e.name)}<div><h3>${esc(e.name)}${e.opponent ? ` vs ${esc(e.opponent)}` : ''}</h3><p>${fmtDate(e.event_date)} · ${e.photos?.[0]?.count || 0} fotos · ${e.published ? 'PUBLICADO' : 'OCULTO'}</p></div><div class="row-actions"><a class="small-button" href="galeria.html?evento=${e.id}" target="_blank">Ver</a><button class="small-button" data-event-edit="${e.id}">Editar</button><button class="small-button" data-event-toggle="${e.id}">${e.published ? 'Ocultar' : 'Publicar'}</button><button class="small-button danger" data-event-delete="${e.id}">Eliminar</button></div></article>`).join('') : '<p class="admin-empty">Todavía no creaste eventos.</p>'}</div></section></div>`; bindEventsPage();
  }
  function bindEventsPage() {
    const form = content().querySelector('#event-form'); form?.addEventListener('submit', async (e) => {
      e.preventDefault(); if (!form.reportValidity()) return; const button = form.querySelector('[type=submit]'); const fd = new FormData(form); const id = fd.get('id'); const values = { club_id: fd.get('club_id'), name: fd.get('name').trim(), opponent: fd.get('opponent').trim() || null, event_date: fd.get('event_date'), event_time: fd.get('event_time') || null, venue: fd.get('venue').trim() || null, description: fd.get('description').trim() || null, default_price_ars: Number(fd.get('default_price_ars')), published: fd.has('published'), featured: fd.has('featured') }; UI.setLoading(button, true);
      try { const event = id ? await AppData.updateEvent(id, values) : await AppData.createEvent(values); const cover = await uploadCover(fd.get('cover'), 'event-covers', event.id); if (cover) await AppData.updateEvent(event.id, { cover_path: cover }); UI.toast('Evento guardado.', 'success'); eventsPage(); } catch (error) { UI.toast(error.message || 'No pudimos guardar el evento.'); console.error(error); } finally { UI.setLoading(button, false); }
    });
    content().addEventListener('click', async (e) => {
      if (e.target.matches('[data-reset-event]')) return eventsPage(); const id = e.target.dataset.eventEdit || e.target.dataset.eventToggle || e.target.dataset.eventDelete; if (!id) return; const event = state.events.find(x => x.id === id);
      try { if (e.target.dataset.eventEdit) eventsPage(event); if (e.target.dataset.eventToggle) { await AppData.updateEvent(id, { published: !event.published }); UI.toast('Estado actualizado.', 'success'); eventsPage(); } if (e.target.dataset.eventDelete && confirm(`¿Eliminar “${event.name}”? Se borrarán también sus fotos y archivos. Esta acción no se puede deshacer.`)) { await AppData.deleteEvent(id); UI.toast('Evento eliminado.', 'success'); eventsPage(); } } catch (error) { UI.toast(error.message || 'No se pudo completar la acción.'); }
    });
  }
  async function uploadPage() {
    await refreshCore(); const eventOptions = state.events.map(e => `<option value="${e.id}">${esc(e.clubs?.name || '')} — ${esc(e.name)}${e.opponent ? ` vs ${esc(e.opponent)}` : ''}</option>`).join('');
    content().innerHTML = `${head('Subir fotografías', 'Elegí el evento, el precio y todas las fotos a la vez.')}<div class="admin-card" style="max-width:860px"><form id="upload-form"><div class="admin-form-grid"><label class="full">Evento<select name="event_id" required><option value="">Seleccionar evento</option>${eventOptions}</select></label><label>Precio por foto (ARS)<input name="price" type="number" min="0" step="1" value="${PRECIOS.FOTO_INDIVIDUAL}" required></label><label>Fotografías originales<input class="file-input" name="files" type="file" accept="image/jpeg,image/png,image/webp" multiple required></label></div><p class="admin-note">Se sube el archivo original al espacio privado <b>originals</b> y se crea una previsualización WebP con marca de agua en <b>previews</b>. Podés cargar de a cientos: se procesan de a 3 para no saturar el navegador.</p><div class="upload-file-list" id="upload-file-list"></div><button class="button button-primary" type="submit">Subir fotografías</button></form></div>`;
    const form = content().querySelector('#upload-form'); const picker = form.elements.files; picker.addEventListener('change', () => renderChosenFiles(picker.files)); form.addEventListener('submit', handleBatchUpload);
  }
  function renderChosenFiles(files) { const host = content().querySelector('#upload-file-list'); host.innerHTML = [...files].map((file, i) => `<div class="upload-file" data-file="${i}"><img src="${URL.createObjectURL(file)}" alt=""><span>${esc(file.name)}<small>${Math.round(file.size/1024/1024*10)/10} MB</small></span><b>Pendiente</b></div>`).join('') || ''; }
  function fileStatus(index, message, type = '') { const el = content().querySelector(`[data-file="${index}"] b`); if (el) { el.textContent = message; el.className = type ? `status-${type}` : ''; } }
  function createWatermarkedPreview(file) { return new Promise((resolve, reject) => { const url = URL.createObjectURL(file); const img = new Image(); img.onload = () => { try { const max = 1600; const scale = Math.min(1, max / Math.max(img.naturalWidth, img.naturalHeight)); const w = Math.round(img.naturalWidth * scale), h = Math.round(img.naturalHeight * scale); const canvas = document.createElement('canvas'); canvas.width = w; canvas.height = h; const ctx = canvas.getContext('2d'); ctx.drawImage(img, 0, 0, w, h); const wm = CONFIG.MARCA_DE_AGUA; const size = Math.max(18, Math.round(w * wm.tamano)); ctx.font = `800 ${size}px Manrope, Arial`; ctx.fillStyle = `rgba(255,255,255,${wm.opacidad})`; ctx.textBaseline = 'middle'; const pad = Math.round(size*.65); const tw = ctx.measureText(wm.texto).width; let x = w/2, y = h/2; if (wm.posicion.includes('right')) x = w-pad-tw/2; if (wm.posicion.includes('left')) x = pad+tw/2; if (wm.posicion.includes('bottom')) y = h-pad; if (wm.posicion.includes('top')) y = pad; ctx.textAlign = 'center'; ctx.fillText(wm.texto, x, y); canvas.toBlob(blob => { URL.revokeObjectURL(url); blob ? resolve(blob) : reject(new Error('No se pudo crear la previsualización.')); }, 'image/webp', .82); } catch (error) { reject(error); } }; img.onerror = () => reject(new Error(`No pudimos leer ${file.name}.`)); img.src = url; }); }
  async function handleBatchUpload(e) {
    e.preventDefault(); const form = e.currentTarget; if (!form.reportValidity()) return; const event = state.events.find(x => x.id === form.elements.event_id.value); const price = Number(form.elements.price.value); const files = [...form.elements.files.files]; const button = form.querySelector('[type=submit]'); if (!event || !files.length) return; UI.setLoading(button, true, 'Preparando carga…');
    let next = 0, succeeded = 0; const worker = async () => { while (next < files.length) { const index = next++; const file = files[index]; fileStatus(index, 'Procesando…'); try { if (file.size > 50 * 1024 * 1024) throw new Error('El archivo supera el límite gratuito de 50 MB.'); const uuid = crypto.randomUUID(); const clean = AppData.safeName(file.name); const extension = clean.includes('.') ? clean.split('.').pop() : 'jpg'; const originalPath = `${event.id}/${uuid}-${clean}`; const previewPath = `${event.id}/${uuid}.webp`; const preview = await createWatermarkedPreview(file); fileStatus(index, 'Subiendo…'); await AppData.upload('originals', originalPath, file); await AppData.upload('previews', previewPath, preview); await AppData.createPhoto({ event_id: event.id, file_name: file.name, photo_code: file.name`, price_ars: price, published: true, preview_path: previewPath, original_path: originalPath, mime_type: file.type, original_extension: extension }); fileStatus(index, 'Listo', 'ok'); succeeded++; } catch (error) { console.error(error); fileStatus(index, 'Error', 'error'); } } };
    try { await Promise.all(Array.from({ length: Math.min(3, files.length) }, worker)); UI.toast(`${succeeded} de ${files.length} fotografías fueron cargadas.`, succeeded === files.length ? 'success' : ''); if (succeeded === files.length) form.reset(); }
    finally { UI.setLoading(button, false); }
  }
  async function photosPage() {
    await refreshPhotos(); const rows = state.photos;
    content().innerHTML = `${head('Fotografías', 'Seleccioná varias fotos para cambiar precio, publicar, ocultar o eliminar.')}<div class="bulk-toolbar"><b id="selection-count">0 seleccionadas</b><input id="bulk-price" min="0" type="number" placeholder="Nuevo precio"><button class="small-button" data-bulk="price">Aplicar precio</button><button class="small-button" data-bulk="publish">Publicar</button><button class="small-button" data-bulk="hide">Ocultar</button><button class="small-button danger" data-bulk="delete">Eliminar</button></div><div class="photo-table-wrap"><table class="photo-table"><thead><tr><th><input type="checkbox" id="all-photos" aria-label="Seleccionar todas"></th><th>Vista</th><th>Foto</th><th>Evento</th><th>Precio</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(p => `<tr><td><input class="photo-select" value="${p.id}" type="checkbox" aria-label="Seleccionar ${esc(p.photo_code)}"></td><td>${UI.image(p.preview_path, p.photo_code)}</td><td><b>${esc(p.photo_code || p.file_name)}</b><br><small>${esc(p.file_name)}</small></td><td>${esc(p.events?.name || '')}</td><td>${money(p.price_ars)}</td><td>${p.published ? 'Publicada' : 'Oculta'}</td><td class="row-actions"><button class="small-button" data-photo-edit="${p.id}">Editar</button><button class="small-button danger" data-photo-delete="${p.id}">Eliminar</button></td></tr>`).join('') || `<tr><td colspan="7" class="admin-empty">Todavía no hay fotografías cargadas.</td></tr>`}</tbody></table></div>`;
    bindPhotosPage();
  }
  function selectedPhotoRows() { const ids = [...content().querySelectorAll('.photo-select:checked')].map(x => x.value); return state.photos.filter(p => ids.includes(p.id)); }
  function selectionText() { const n = selectedPhotoRows().length; const label = content().querySelector('#selection-count'); if (label) label.textContent = `${n} seleccionada${n === 1 ? '' : 's'}`; }
  function bindPhotosPage() {
    content().querySelector('#all-photos')?.addEventListener('change', (e) => { content().querySelectorAll('.photo-select').forEach(box => box.checked = e.target.checked); selectionText(); }); content().querySelectorAll('.photo-select').forEach(box => box.addEventListener('change', selectionText));
    content().addEventListener('click', async (e) => { const action = e.target.dataset.bulk; const photoId = e.target.dataset.photoEdit || e.target.dataset.photoDelete; try {
      if (action) { const rows = selectedPhotoRows(); if (!rows.length) return UI.toast('Seleccioná al menos una fotografía.'); if (action === 'price') { const val = content().querySelector('#bulk-price').value; if (val === '') return UI.toast('Indicá el nuevo precio.'); await AppData.updatePhotos(rows.map(x => x.id), { price_ars: Number(val) }); } if (action === 'publish') await AppData.updatePhotos(rows.map(x => x.id), { published: true }); if (action === 'hide') await AppData.updatePhotos(rows.map(x => x.id), { published: false }); if (action === 'delete') { if (!confirm(`¿Eliminar ${rows.length} fotografías y sus archivos originales? Esta acción no se puede deshacer.`)) return; await AppData.deletePhotos(rows); } UI.toast('Cambios aplicados.', 'success'); photosPage(); }
      if (e.target.dataset.photoEdit) { const photo = state.photos.find(p => p.id === photoId); const input = prompt(`Nuevo precio para ${photo.photo_code}:`, photo.price_ars); if (input !== null && input !== '') { await AppData.updatePhotos([photoId], { price_ars: Number(input) }); UI.toast('Precio actualizado.', 'success'); photosPage(); } }
      if (e.target.dataset.photoDelete) { const photo = state.photos.find(p => p.id === photoId); if (confirm(`¿Eliminar ${photo.photo_code} y sus archivos? Esta acción no se puede deshacer.`)) { await AppData.deletePhotos([photo]); UI.toast('Fotografía eliminada.', 'success'); photosPage(); } }
    } catch (error) { UI.toast(error.message || 'No pudimos aplicar los cambios.'); console.error(error); } });
  }
  async function ordersPage() {
    await refreshOrders(); content().innerHTML = `${head('Pedidos', 'Los pedidos se generan desde el checkout y llegan a tu WhatsApp.')}<div class="order-list">${state.orders.map(o => `<article class="order-card-admin"><header><div><h3>#${o.order_number} · Pedido por WhatsApp</h3><p>${fmtDate(o.created_at?.slice(0,10))}</p></div><select data-order-status="${o.id}"><option value="new" ${selected('new',o.status)}>Nuevo</option><option value="contacted" ${selected('contacted',o.status)}>Contactado</option><option value="paid" ${selected('paid',o.status)}>Pagado</option><option value="delivered" ${selected('delivered',o.status)}>Entregado</option><option value="cancelled" ${selected('cancelled',o.status)}>Cancelado</option></select></header><ul>${(o.order_items || []).map(i => `<li>${esc(i.photo_code || i.photos?.photo_code || 'Foto')} — ${money(i.price_ars)}</li>`).join('')}</ul><b>Total: ${money(o.total_ars)}</b></article>`).join('') || '<div class="admin-card admin-empty">Aún no recibiste pedidos.</div>'}</div>`; content().querySelectorAll('[data-order-status]').forEach(select => select.addEventListener('change', async () => { try { await AppData.updateOrder(select.dataset.orderStatus, select.value); UI.toast('Estado del pedido actualizado.', 'success'); } catch (error) { UI.toast(error.message || 'No se pudo actualizar el pedido.'); } }));
  }
  async function verifyAdmin() { const user = await AppData.currentUser(); if (!user) return null; const profile = await AppData.profile(); if (profile.role !== 'admin') { await AppData.signOut(); throw new Error('Esta cuenta no tiene permiso de administrador.'); } return user; }
  document.addEventListener('DOMContentLoaded', async () => {
    const login = document.querySelector('#admin-login'), panel = document.querySelector('#admin-panel');
    if (!AppData.configured()) { login.querySelector('form').hidden = true; login.querySelector('.form-help').textContent = 'Primero configurá Supabase en js/config.js y ejecutá supabase/schema.sql. Consultá el README.'; return; }
    async function showPanel(user) { login.hidden = true; panel.hidden = false; document.querySelector('#admin-email').textContent = user.email; await render(); }
    try { const user = await verifyAdmin(); if (user) await showPanel(user); } catch (error) { UI.toast(error.message); }
    document.querySelector('#login-form').addEventListener('submit', async (e) => { e.preventDefault(); const form = e.currentTarget; if (!form.reportValidity()) return; const button = form.querySelector('[type=submit]'); UI.setLoading(button, true, 'Ingresando…'); try { const values = Object.fromEntries(new FormData(form)); await AppData.signIn(values.email, values.password); const user = await verifyAdmin(); await showPanel(user); } catch (error) { await AppData.signOut().catch(() => {}); UI.toast(error.message || 'No pudimos iniciar sesión.'); } finally { UI.setLoading(button, false); } });
    document.querySelector('#logout').addEventListener('click', async () => { await AppData.signOut(); location.reload(); }); document.querySelector('#admin-nav').addEventListener('click', e => { const b = e.target.closest('[data-tab]'); if (b) { setTab(b.dataset.tab); document.querySelector('#admin-nav').classList.remove('open'); } }); document.querySelector('#admin-menu').addEventListener('click', () => document.querySelector('#admin-nav').classList.toggle('open'));
  });
})();
